---
- name: "Converge existing Compose paths"
  hosts: all
  gather_facts: false
  become: false
  vars:
    compose_deploy_nginx_server_name: existing-paths.test.local
    compose_deploy_volumes_dir:
      - path: /app/db
        mode: "0755"
    compose_deploy_projects:
      - name: flask
        src: "{{ playbook_dir }}/../default/files/flask/"
        dest: /app/flask
        directory_mode: "0755"

  roles:
    - role: bouola.compose_deploy
