---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "bouola-compose-deploy-${os:-ubuntu2204}-${scenario:-default}"
    image: "${image:-dcagatay/ubuntu-dind}:${tag:-22.04}"
    privileged: true
    pre_build_image: true
    tty: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "true"
    ANSIBLE_CALLBACKS_ENABLED: "ansible.posix.profile_tasks"
    ANSIBLE_STDOUT_CALLBACK: "ansible.builtin.debug"
  options:
    v: true

verifier:
  name: ansible
